### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MikeRosoft** [Kermalis/EndianBinaryIO#27]
What license of this library under? It would be good to add a license file to the project - either publish it under a permissive license, or, alternately, under LGPL license (the library is being used by https://github.com/Kermalis/VGMusicStudio project, whose source code is under LGPL license).

**Comment by Kermalis** [comment]
Hello, I don't really understand licenses, but you're free to use this however you wish, as long as you're not stealing my work :)
I'll look into the license at some point
